# Code 2
- Basic Imputation for Numerical and Categorial
- Logistic Model (Balanced/ Unbalanced)

## 1/ Import Libraries

In [1]:
#CodeSection1
from google.colab import drive
drive.mount('/mntDrive')

Mounted at /mntDrive

In [2]:
#CodeSection2
import pandas as pd

## 2/ Import Data

In [3]:
#CodeSection3
train = pd.read_csv("/mntDrive/MyDrive/__Data_Science/1 Loan Prediction/input/train.csv")
test = pd.read_csv("/mntDrive/MyDrive/__Data_Science/1 Loan Prediction/input/test.csv")

### Check Train Data

In [4]:
#CodeSection4
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

### Check Test Data

In [5]:
#CodeSection4
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             356 non-null    object
 2   Married            367 non-null    object
 3   Dependents         357 non-null    object
 4   Education          367 non-null    object
 5   Self_Employed      344 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB

### We Combine both Datasets to perform Missing Value Imputation

In [6]:
#CodeSection6
all_data = [train, test]
all_data

[      Loan_ID  Gender Married  ... Credit_History Property_Area Loan_Status
 0    LP001002    Male      No  ...            1.0         Urban           Y
 1    LP001003    Male     Yes  ...            1.0         Rural           N
 2    LP001005    Male     Yes  ...            1.0         Urban           Y
 3    LP001006    Male     Yes  ...            1.0         Urban           Y
 4    LP001008    Male      No  ...            1.0         Urban           Y
 ..        ...     ...     ...  ...            ...           ...         ...
 609  LP002978  Female      No  ...            1.0         Rural           Y
 610  LP002979    Male     Yes  ...            1.0         Rural           Y
 611  LP002983    Male     Yes  ...            1.0         Urban           Y
 612  LP002984    Male     Yes  ...            1.0         Urban           Y
 613  LP002990  Female      No  ...            0.0     Semiurban           N

 [614 rows x 13 columns],
       Loan_ID Gender Married  ... Loan_Amount_Term Credit_History Property_Area
 0    LP001015   Male     Yes  ...            360.0            1.0         Urban
 1    LP001022   Male     Yes  ...            360.0            1.0         Urban
 2    LP001031   Male     Yes  ...            360.0            1.0         Urban
 3    LP001035   Male     Yes  ...            360.0            NaN         Urban
 4    LP001051   Male      No  ...            360.0            1.0         Urban
 ..        ...    ...     ...  ...              ...            ...           ...
 362  LP002971   Male     Yes  ...            360.0            1.0         Urban
 363  LP002975   Male     Yes  ...            360.0            1.0         Urban
 364  LP002980   Male      No  ...            360.0            NaN     Semiurban
 365  LP002986   Male     Yes  ...            360.0            1.0         Rural
 366  LP002989   Male      No  ...            180.0            1.0         Rural

 [367 rows x 12 columns]]

In [7]:
#CodeSection7
# Combine both using concat (with axis = 0) to check Missing Value
pd.concat([train, test], axis = 0).isnull().sum()

Loan_ID                0
Gender                24
Married                3
Dependents            25
Education              0
Self_Employed         55
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount            27
Loan_Amount_Term      20
Credit_History        79
Property_Area          0
Loan_Status          367
dtype: int64

## 3/ Impute Numerical Variables
- Impute all Numerical Variables

In [8]:
     #LoanAmount, Loan_Amount_Term, Credit_History

### Variable/Feature 1

In [11]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
for dataset in all_data:
  dataset['LoanAmount'] = dataset['LoanAmount'].fillna(train['LoanAmount'].median())
  dataset['Loan_Amount_Term'] = dataset['Loan_Amount_Term'].fillna(train['Loan_Amount_Term'].median())
  dataset['Credit_History'] = dataset['Credit_History'].fillna(train['Credit_History'].median())

### Variable/Feature 2

In [12]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
pd.concat([train, test], axis = 0).isnull().sum()

Loan_ID                0
Gender                24
Married                3
Dependents            25
Education              0
Self_Employed         55
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount             0
Loan_Amount_Term       0
Credit_History         0
Property_Area          0
Loan_Status          367
dtype: int64

### Variable/Feature 3

In [ ]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
<Write your code here>

### Variable/Feature 4

In [ ]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
<Write your code here>

## 4/ Impute Categorical Variables
- Impute all Numerical Variables

### Categorical Variable/Feature 1

In [ ]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
#Married, Dependents, Gender, Self_Employed

### Categorical Variable/Feature 2

In [13]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
for dataset in all_data:
  dataset['Married'] = dataset['Married'].fillna(train['Married'].mode()[0])
  dataset['Dependents'] = dataset['Dependents'].fillna(train['Dependents'].mode()[0])
  dataset['Gender'] = dataset['Gender'].fillna(train['Gender'].mode()[0])
  dataset['Self_Employed'] = dataset['Self_Employed'].fillna(train['Self_Employed'].mode()[0])

### Categorical Variable/Feature 3

In [ ]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
<Write your code here>

### Categorical Variable/Feature 4

In [ ]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
<Write your code here>

## 5/ Now Re Check all of them

In [14]:
#CodeSection10
# Combine both to check Missing Value
pd.concat([train, test], axis = 0).isnull().sum()

Loan_ID                0
Gender                 0
Married                0
Dependents             0
Education              0
Self_Employed          0
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount             0
Loan_Amount_Term       0
Credit_History         0
Property_Area          0
Loan_Status          367
dtype: int64

## 6/ Prepare Data for Model Model

In [15]:
#CodeSection11
# Check first 5 rows of Test Dataset
test.head()

    Loan_ID Gender Married  ... Loan_Amount_Term Credit_History Property_Area
0  LP001015   Male     Yes  ...            360.0            1.0         Urban
1  LP001022   Male     Yes  ...            360.0            1.0         Urban
2  LP001031   Male     Yes  ...            360.0            1.0         Urban
3  LP001035   Male     Yes  ...            360.0            1.0         Urban
4  LP001051   Male      No  ...            360.0            1.0         Urban

[5 rows x 12 columns]

In [16]:
#CodeSection12
# Divide Data into X and y
X = train.drop(['Loan_ID','Loan_Status'], axis=1)
y = train['Loan_Status']

### Create Dummy Variables for  Categorical Variables

In [18]:
#CodeSection13
# Create Dummy Variables
X = pd.get_dummies(X)

In [19]:
#CodeSection14
# Check first 5 rows of X
X.head()

   ApplicantIncome  ...  Property_Area_Urban
0             5849  ...                    1
1             4583  ...                    0
2             3000  ...                    1
3             2583  ...                    1
4             6000  ...                    1

[5 rows x 20 columns]

## 7/ Build Model

In [24]:
#CodeSection15
#Start by importing LogisticRegression 
from sklearn.linear_model import LogisticRegression

#Initialize LogisticRegression
clf = LogisticRegression(max_iter=1000)

In [25]:
#CodeSection16
# Fit Model
model = clf.fit(X,y)

### Check Accuracy of Model on Train Data

In [26]:
#CodeSection17
# Predict on Train Data and check predictions
y_pred = model.predict(X)
y_pred

array(['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N',
       'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N'], dtype=object)

### We can use a Accuracy Function from Metrics

In [27]:
#CodeSection17
# Import accuracy_score 
from sklearn.metrics import accuracy_score

In [28]:
#CodeSection18
# Get Actual Predictions
y_true = y

In [29]:
#CodeSection19
# Compare True values versus prediction we made
print(f" Train Accuracy : {accuracy_score(y_true, y_pred):0.1%}")

 Train Accuracy : 81.1%

## 8/ Prediction and Submission

### Predict

In [32]:
#CodeSection20
# Get X variables from the Test Dataset
X_test = test.drop(['Loan_ID'], axis=1)

In [33]:
#CodeSection21
#Covert to Dummies
X_test = pd.get_dummies(X_test)

In [34]:
#CodeSection22
# Predict (Y/N) on X Variables of Test Dataset
X_test_pred = model.predict(X_test)

### Import Sample Submission

In [35]:
#CodeSection23
sample_submission = pd.read_csv("/mntDrive/MyDrive/__Data_Science/1 Loan Prediction/input/sample_submission.csv")
sample_submission

      Loan_ID Loan_Status
0    LP001015           N
1    LP001022           N
2    LP001031           N
3    LP001035           N
4    LP001051           N
..        ...         ...
362  LP002971           N
363  LP002975           N
364  LP002980           N
365  LP002986           N
366  LP002989           N

[367 rows x 2 columns]

### Create a Submission

In [36]:
#CodeSection24
submission = pd.DataFrame({
    'Loan_ID' : test['Loan_ID'],
    'Loan_Status' : X_test_pred
})

### Export Submission File

In [37]:
#CodeSection25
submission.to_csv('/mntDrive/MyDrive/__Data_Science/1 Loan Prediction/output/O2_LR_Basic_Impute.csv', index = False)

In [ ]:
# LB Accuracy : <Write your score here>